### ISSUE TITLE
Typescript 4 Build Error

### ISSUE THREAD

**Issue by mcdenhoed** [pixijs/filters#301]
Hi!

I'm using pixi in a typescript project, along with the `advanced-bloom-filter`. I am currently on pixi.js 5.3.9, and @pixi/filter-advanced-bloom 3.2.0, and am trying to update to pixi 6.0.4 and advanced-bloom 4.1.0.

I'm using Typescript 4.1 and am getting the following error when I try to bump pixi advanced bloom from 3.2 to 4:

```
Error: node_modules/@pixi/filter-advanced-bloom/index.d.ts:55:9 - error TS2611: 'resolution' is defined as a property in class 'Filter', but is overridden here in 'AdvancedBloomFilter' as an accessor.
55     get resolution(): number;
           ~~~~~~~~~~
```

This seems to be caused by https://github.com/microsoft/TypeScript/pull/37894 which introduced an error when overriding a property with an accessor.

The property in question:

https://github.com/pixijs/pixijs/blob/25c38116e3bd27e96eb9071bb2265ce113f33219/packages/core/src/filters/Filter.ts#L219-L225

The accessor override in `AdvancedBloomFilter` that typescript is complaining about:

https://github.com/pixijs/filters/blob/b64ddd949b4d2ee864ab96ce4daa6a549b786064/filters/advanced-bloom/src/AdvancedBloomFilter.ts#L127-L147

I'm not sure what the best solution is here. Maybe changing the base `Filter` definition to an accessor and having a private `_resolution` property like in `AdvancedBloomFilter`, though no idea if that would break other filters (since overwriting an accessor with a property is also an error).

**Comment by mcdenhoed** [comment]
Resolved in https://github.com/pixijs/pixijs/pull/7769.
